#@data/values
---
projectName: bpt-node-job
resourceType: Job
hasIngress: False
useHttp: True
jobAdditionalConfig:
  parallelism: 1
  backoffLimit: 2
  activeDeadlineSeconds: 23444
additionalDeployEnvSources:
  - configMapRef:
      name: config-1
  - configMapRef:
      name: config-2
  - configMapRef:
      name: config-2
  - secretRef:
      name: bi-productive-prod-back
      optional: false
configMaps:
  - name: config-1
    data:
      PROP_1: 'asd'
      PROP_2: 'bcv'
  - name: config-2
    data:
      PROP_2_1: '2_asd'
      PROP_2_2: '2_bcv'
